---

name: github-pages

# This workflow builds the Docusaurus documentation and deploys it to GitHub Pages.

# When you configure a custom domain for GitHub Pages (via repository Settings → Pages → Custom domain),
# GitHub stores this information in a CNAME file in your repository, but it doesn't automatically
# create an Actions variable for it.

on:
  # manual trigger
  workflow_dispatch:
  # push or merge to master
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "github-pages"
  cancel-in-progress: false

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      # ----
      - name: 'Setup Node.js'
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: docs/pages/package-lock.json
      # ----
      - name: 'Install dependencies'
        working-directory: docs/pages
        run: npm ci
      - name: 'Gather documentation from source directories'
        working-directory: docs/pages
        run: npm run assemble-docs
      - name: 'Build Docusaurus static files'
        working-directory: docs/pages
        env:
          DOCUSAURUS_TITLE: ${{ github.event.repository.name }}
          DOCUSAURUS_URL: 'https://${{ github.repository_owner }}.github.io'
          DOCUSAURUS_BASE_URL: '/${{ github.event.repository.name }}/'
        run: npm run build
      # ----
      - name: 'Setup Pages'
        uses: actions/configure-pages@v5
        with:
          token: ${{ github.token }}
      - name: 'Upload artifact'
        uses: actions/upload-pages-artifact@v4
        with:
          name: 'github-pages'
          path: docs/pages/build

  deploy:
    name: deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 'Generate GitHub App Token'
        id: generate_token
        if: ${{ vars.RELEASE_APP_ID }}
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
      - name: 'Deploy to GitHub Pages'
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ steps.generate_token.outputs.token || secrets.GITHUB_TOKEN }}
          artifact_name: 'github-pages'
